{
 "title": "Lukso Validator2",
 "description": "Dashboard edited by Bitcrusher to suit Lukso Validator",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Network Status",
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Server",
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Total Validator Balance (LYX)",
   "type": "stat",
   "description": "Sum of all validator balances.",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "LYX" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_balance{job=\"validator\"})",
     "legendFormat": "vbal"
    }
   ]
  },
  {
   "title": "Total Earnings (LYX)",
   "type": "stat",
   "description": "Total LYX return on the initial effective stake of active local validators.\n\n#NEEDS EDITING",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "LYX" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_balance{job=\"validator\"})-(count(validator_balance{job=\"validator\"} > 16 and validator_statuses{job=\"validator\"} == 3)*32)"
    }
   ]
  },
  {
   "title": "Total Return",
   "type": "stat",
   "description": "Total percentage return on the initial effective stake of active local validators. Excess deposits will be reflected as earnings.",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(validator_balance{job=\"validator\"}) - (count(validator_balance{job=\"validator\"} > 16 and validator_statuses{job=\"validator\"} == 3)*32))/(count(validator_balance{job=\"validator\"} > 16 and validator_statuses{job=\"validator\"} == 3)*32)  "
    }
   ]
  },
  {
   "title": "Total Peer Count",
   "type": "stat",
   "description": "Number of beacon nodes to which this node is connected.",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "peers" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "p2p_peer_count{state=\"Connected\",job=\"beacon node\"}"
    }
   ]
  },
  {
   "title": "Participation Rate",
   "type": "stat",
   "description": "The percentage of LYX balances expected to attest that are actually attesting.",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(beacon_prev_epoch_target_gwei{job=\"beacon node\"} / beacon_prev_epoch_active_gwei{job=\"beacon node\"} )"
    }
   ]
  },
  {
   "title": "Network Liveness",
   "type": "stat",
   "description": "A metric expressing the distance between the current finalized epoch and the expected finalized epoch based on the genesis time. 100% means the expected and current finalized epochs are the same. The metric reaches 0% when the finalized epoch is 25 epochs behind the expected epoch.",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min((1-(4*((floor(beacon_clock_time_slot{job=\"beacon node\"}/32) - beacon_finalized_epoch{job=\"beacon node\"} - 2)/100))),0)"
    }
   ]
  },
  {
   "title": "Epochs",
   "type": "stat",
   "description": "Current and finalized epochs. In this order, these three values should be sequentially decreasing.",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(beacon_clock_time_slot{job=\"beacon node\"} / 32)",
     "legendFormat": "current"
    },
    {
     "expr": "beacon_finalized_epoch {job=\"beacon node\"} ",
     "legendFormat": "finalized"
    }
   ]
  },
  {
   "title": "Slots",
   "type": "stat",
   "description": "Current slot and head slot",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "beacon_slot{job=\"beacon node\"}",
     "legendFormat": "Current"
    },
    {
     "expr": "beacon_head_slot{job=\"beacon node\"}",
     "legendFormat": "Head"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "CPU usage on the server",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "node_cpu_scaling_frequency_hertz{cpu=\"0\", instance=\"localhost:9100\", job=\"node\"}",
     "legendFormat": "CPU 1"
    },
    {
     "expr": "node_cpu_scaling_frequency_hertz{cpu=\"1\", instance=\"localhost:9100\", job=\"node\"}",
     "legendFormat": "CPU 2"
    },
    {
     "expr": "node_cpu_scaling_frequency_hertz{cpu=\"2\", instance=\"localhost:9100\", job=\"node\"}\r\n",
     "legendFormat": "CPU 3"
    },
    {
     "expr": "node_cpu_scaling_frequency_hertz{cpu=\"3\", instance=\"localhost:9100\", job=\"node\"}\r\n",
     "legendFormat": "CPU 4"
    },
    {
     "expr": "node_cpu_scaling_frequency_hertz{cpu=\"4\", instance=\"localhost:9100\", job=\"node\"}\r\n",
     "legendFormat": "CPU 5"
    },
    {
     "expr": "node_cpu_scaling_frequency_hertz{cpu=\"5\", instance=\"localhost:9100\", job=\"node\"}\r\n",
     "legendFormat": "CPU 6"
    },
    {
     "expr": "node_cpu_scaling_frequency_hertz{cpu=\"6\", instance=\"localhost:9100\", job=\"node\"}\r\n",
     "legendFormat": "CPU 7"
    },
    {
     "expr": "node_cpu_scaling_frequency_hertz{cpu=\"7\", instance=\"localhost:9100\", job=\"node\"}\r\n",
     "legendFormat": "CPU 8"
    }
   ]
  },
  {
   "title": "Total Validator Balance (USD)",
   "type": "stat",
   "description": "Sum of all validator balances multiplied by the price of LYX in USD.",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_balance{job=\"validator\"})",
     "legendFormat": "balance"
    },
    { "expr": "lyxusd", "legendFormat": "lyxusd" },
    { "expression": "$A * $B", "type": "math" }
   ]
  },
  {
   "title": "Total Earnings (USD)",
   "type": "stat",
   "description": "Total earnings in USD.",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_balance{job=\"validator\"})-(count(validator_balance{job=\"validator\"} > 16 and validator_statuses{job=\"validator\"} == 3)*32)",
     "legendFormat": "total_balance"
    },
    { "expr": "lyxusd", "legendFormat": "lyxusd" },
    { "expression": "$A * $B", "type": "math" }
   ]
  },
  {
   "title": "Total Earnings (USD)",
   "type": "stat",
   "description": "Total earnings in USD.",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_balance{job=\"validator\"})-(count(validator_balance{job=\"validator\"} > 16 and validator_statuses{job=\"validator\"} == 3)*32)",
     "legendFormat": "total_balance"
    },
    { "expr": "lyxusd", "legendFormat": "lyxusd" },
    { "expression": "$A * $B", "type": "math" }
   ]
  },
  {
   "title": "Max. Inactivity Score",
   "type": "stat",
   "description": "Current maximum inactvity score across all validators.",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(validator_inactivity_score)"
    }
   ]
  },
  {
   "title": "Network Validators",
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Local Validators",
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Validator Counts",
   "type": "stat",
   "description": "Counts of active, slashed and exited validators.",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "validator_count{state=\"Active\",job=\"beacon node\"} ",
     "legendFormat": "active"
    },
    {
     "expr": "validator_count{state=\"Slashed\",job=\"beacon node\"} ",
     "legendFormat": "slashed"
    },
    {
     "expr": "validator_count{state=\"Exited\",job=\"beacon node\"} ",
     "legendFormat": "exited"
    }
   ]
  },
  {
   "title": "Avg. Balance",
   "type": "stat",
   "description": "Average validator balance across the network",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "validators_total_balance{state=\"Active\",job=\"beacon node\"} / validator_count{state=\"Active\",job=\"beacon node\"} / 1000000000",
     "legendFormat": "lyx"
    }
   ]
  },
  {
   "title": "Queue Lengths",
   "type": "stat",
   "description": "Estimated length of time until all pending and exiting validators have cleared the queues.",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((validator_count{state=\"Pending\",job=\"beacon node\"}/6)*6.4)",
     "legendFormat": "pending"
    },
    {
     "expr": "((validator_count{state=\"Exiting\",job=\"beacon node\"}/6)*6.4)",
     "legendFormat": "exiting"
    }
   ]
  },
  {
   "title": "Validator Queues",
   "type": "stat",
   "description": "Current number of pending and exiting validators",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "validator_count{state=\"Pending\",job=\"beacon node\"}",
     "legendFormat": "pending"
    },
    {
     "expr": "validator_count{state=\"Exiting\",job=\"beacon node\"}",
     "legendFormat": "exiting"
    }
   ]
  },
  {
   "title": "Hourly Earnings",
   "type": "stat",
   "description": "Increase in all local validator balances over the last hour",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "LYX" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_balance{job=\"validator\"}) - sum(validator_balance{job=\"validator\"} offset 1h != 0) - (32 * count(validator_balance{job=\"validator\"} > 16)) + (32 * count(validator_balance{job=\"validator\"} offset 1h > 16))"
    }
   ]
  },
  {
   "title": "Daily Earnings (LYX)",
   "type": "stat",
   "description": "Increase in all local validator balances over the last day",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "LYX" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_balance{job=\"validator\"}) - sum(validator_balance{job=\"validator\"} offset 1d != 0) - (32 * count(validator_balance{job=\"validator\"} > 16)) + (32 * count(validator_balance{job=\"validator\"} offset 1d > 16))"
    }
   ]
  },
  {
   "title": "Weekly Earnings",
   "type": "stat",
   "description": "Increase in all local validator balances over the last week",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "LYX" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_balance{job=\"validator\"}) - sum(validator_balance{job=\"validator\"} offset 7d != 0) - (32 * count(validator_balance{job=\"validator\"} > 16)) + (32 * count(validator_balance{job=\"validator\"} offset 7d > 16))"
    }
   ]
  },
  {
   "title": "Monthly Earnings",
   "type": "stat",
   "description": "Increase in all local validator balances over the last month",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "LYX" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_balance{job=\"validator\"}) - sum(validator_balance{job=\"validator\"} offset 30d != 0) - (32 * count(validator_balance{job=\"validator\"} > 16)) + (32 * count(validator_balance{job=\"validator\"} offset 30d > 16))"
    }
   ]
  },
  {
   "title": "Hourly Earnings (USD)",
   "type": "stat",
   "description": "Price of LYX in USD.",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_balance{job=\"validator\"}) - sum(validator_balance{job=\"validator\"} offset 1h != 0) - (32 * count(validator_balance{job=\"validator\"} > 16)) + (32 * count(validator_balance{job=\"validator\"} offset 1h > 16)) * count(lyxusd)",
     "legendFormat": "balance"
    }
   ]
  },
  {
   "title": "Daily Earnings (USD)",
   "type": "stat",
   "description": "Price of LYX in USD.",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_balance{job=\"validator\"}) - sum(validator_balance{job=\"validator\"} offset 1d != 0) - (32 * count(validator_balance{job=\"validator\"} > 16)) + (32 * count(validator_balance{job=\"validator\"} offset 1d > 16)) * count(lyxusd)",
     "legendFormat": "balance"
    }
   ]
  },
  {
   "title": "Weekly Earnings (USD)",
   "type": "stat",
   "description": "Price of LYX in USD.",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_balance{job=\"validator\"}) - sum(validator_balance{job=\"validator\"} offset 7d != 0) - (32 * count(validator_balance{job=\"validator\"} > 16)) + (32 * count(validator_balance{job=\"validator\"} offset 7d > 16)) * count(lyxusd)",
     "legendFormat": "balance"
    }
   ]
  },
  {
   "title": "Daily Earnings (USD)",
   "type": "stat",
   "description": "Price of LYX in USD.",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_balance{job=\"validator\"}) - sum(validator_balance{job=\"validator\"} offset 30d != 0) - (32 * count(validator_balance{job=\"validator\"} > 16)) + (32 * count(validator_balance{job=\"validator\"} offset 30d > 16)) * count(lyxusd)",
     "legendFormat": "balance"
    }
   ]
  },
  {
   "title": "Client Status",
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Process Uptimes",
   "type": "stat",
   "description": "The length of time the beacon chain and validator processes have been running.",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time()-process_start_time_seconds{job=\"beacon node\"})/3600",
     "legendFormat": "beacon chain"
    },
    {
     "expr": "(time()-process_start_time_seconds{job=\"validator\"})/3600",
     "legendFormat": "validator"
    }
   ]
  },
  {
   "title": "Prysm Versions",
   "type": "table",
   "description": "Versions of the currently running Prysm clients.",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 9 },
   "targets": [
    {
     "expr": "max(prysm_version) by (job, version)"
    }
   ]
  },
  {
   "title": "Validator Logs",
   "type": "stat",
   "description": "Average number of log messages received per hour over the selected time range",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "/hr" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(log_entries_total{job=\"validator\", level=\"error\"}[$__range]))*3600",
     "legendFormat": "errors"
    },
    {
     "expr": "sum(rate(log_entries_total{job=\"validator\", level=\"warning\"}[$__range]))*3600",
     "legendFormat": "warnings"
    }
   ]
  },
  {
   "title": "Beacon Logs",
   "type": "stat",
   "description": "Average number of log messages received per hour over the selected time range",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "/hr" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(log_entries_total{job=\"beacon node\", level=\"error\"}[$__range]))*3600",
     "legendFormat": "errors"
    },
    {
     "expr": "sum(rate(log_entries_total{job=\"beacon node\", level=\"warning\"}[$__range]))*3600",
     "legendFormat": "warnings"
    },
    {}
   ]
  },
  {
   "title": "CPU Temp",
   "type": "timeseries",
   "description": "Current CPU Temperature ",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{chip=\"platform_coretemp_0\", instance=\"localhost:9100\", job=\"node\", sensor=\"temp4\"}",
     "legendFormat": "CPU Temp"
    }
   ]
  },
  {
   "title": "Hourly Return, Annualized",
   "type": "stat",
   "description": "Percentage increase in all local validator balances over the last hour",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum(validator_balance{job=\"validator\"}) - sum(validator_balance{job=\"validator\"} offset 1h != 0) - (32 * count(validator_balance{job=\"validator\"} > 16)) +\t(32 * count(validator_balance{job=\"validator\"} offset 1h > 16)))/(32 * avg_over_time(count(validator_balance{job=\"validator\"} > 16)[1h:]))) * 365 * 24",
     "legendFormat": "annualized hourly return"
    }
   ]
  },
  {
   "title": "Daily Return, Annualized",
   "type": "stat",
   "description": "Percentage increase in all local validator balances over the last day",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum(validator_balance{job=\"validator\"}) - sum(validator_balance{job=\"validator\"} offset 1d != 0) - (32 * count(validator_balance{job=\"validator\"} > 16)) +\t(32 * count(validator_balance{job=\"validator\"} offset 1d > 16)))/(32 * avg_over_time(count(validator_balance{job=\"validator\"} > 16)[1d:]))) * 365",
     "legendFormat": "annualized daily return"
    }
   ]
  },
  {
   "title": "Weekly Return, Annualized",
   "type": "stat",
   "description": "Percentage increase in all local validator balances over the last week",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum(validator_balance{job=\"validator\"}) - sum(validator_balance{job=\"validator\"} offset 7d != 0) - (32 * count(validator_balance{job=\"validator\"} > 16)) +\t(32 * count(validator_balance{job=\"validator\"} offset 7d > 16)))/(32 * avg_over_time(count(validator_balance{job=\"validator\"} > 16)[7d:]))) * (365/7)",
     "legendFormat": "annualized weekly return"
    }
   ]
  },
  {
   "title": "Monthly Return, Annualized",
   "type": "stat",
   "description": "Percentage increase in all local validator balances over the last month",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum(validator_balance{job=\"validator\"}) - sum(validator_balance{job=\"validator\"} offset 30d != 0) - (32 * count(validator_balance{job=\"validator\"} > 16)) +\t(32 * count(validator_balance{job=\"validator\"} offset 30d > 16)))/(32 * avg_over_time(count(validator_balance{job=\"validator\"} > 16)[30d:]))) * (365/30)",
     "legendFormat": "annualized monthly return"
    }
   ]
  },
  {
   "title": "Validator Process Stats",
   "type": "table",
   "description": "validator stats by public key over the lifetime of the validator process ",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "label_replace(max by(pubkey) (validator_statuses{job=\"validator\"}), \"pubkey\", \"$1\", \"pubkey\", \"(.{100}).*\")"
    },
    {
     "expr": "label_replace(max by(pubkey) (validator_balance{job=\"validator\"}), \"pubkey\", \"$1\", \"pubkey\", \"(.{100}).*\")",
     "legendFormat": "balance"
    },
    {
     "expr": "label_replace(max by(pubkey) (validator_successful_proposals{job=\"validator\"}), \"pubkey\", \"$1\", \"pubkey\", \"(.{100}).*\")  "
    },
    {
     "expr": "label_replace(max by(pubkey) (validator_successful_attestations{job=\"validator\"}), \"pubkey\", \"$1\", \"pubkey\", \"(.{100}).*\")  "
    },
    {
     "expr": "label_replace(max by(pubkey) (validator_successful_aggregations{job=\"validator\"}), \"pubkey\", \"$1\", \"pubkey\", \"(.{100}).*\") "
    },
    {
     "expr": "label_replace(max by(pubkey) (validator_failed_attestations{job=\"validator\"}), \"pubkey\", \"$1\", \"pubkey\", \"(.{100}).*\") "
    },
    {
     "expr": "label_replace(max by(pubkey) (validator_failed_aggregations{job=\"validator\"}), \"pubkey\", \"$1\", \"pubkey\", \"(.{100}).*\") "
    },
    {
     "expr": "label_replace(max by(pubkey) (validator_inactivity_score{job=\"validator\"}), \"pubkey\", \"$1\", \"pubkey\", \"(.{100}).*\")  "
    }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "description": "The number of peers to which the beacon chain is connected to (total of inbound and out)",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "p2p_peer_count{state=\"Connected\",job=\"beacon node\"}",
     "legendFormat": "peers"
    }
   ]
  },
  {
   "title": "Client Memory Usage",
   "type": "timeseries",
   "description": "Beacon chain and validator memory usage on the server.",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"beacon node\"}",
     "legendFormat": "beacon memory"
    },
    {
     "expr": "process_resident_memory_bytes{job=\"validator\"}",
     "legendFormat": "validator memory"
    }
   ]
  },
  {
   "title": "Server Memory Usage",
   "type": "timeseries",
   "description": "Memory usage on the server",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"localhost:9100\", job=\"node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"localhost:9100\", job=\"node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "description": "Network transmission (tx) and reception (rx) rates",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{device=\"eno1\", instance=\"localhost:9100\", job=\"node\"}[1m])*8 or irate(node_network_transmit_bytes{device=\"eno1\", instance=\"localhost:9100\", job=\"node\"}[1m])*8 or irate(node_network_transmit_bytes_total{device=\"eno1\", instance=\"localhost:9100\", job=\"node\"}[1m])*8 or irate(node_network_transmit_bytes{device=\"eno1\", instance=\"localhost:9100\", job=\"node\"}[1m])*8",
     "legendFormat": "tx"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"eno1\", instance=\"localhost:9100\", job=\"node\"}[5m])*8 or irate(node_network_receive_bytes{device=\"eno1\", instance=\"localhost:9100\", job=\"node\"}[5m])*8 or irate(node_network_receive_bytes_total{device=\"eno1\", instance=\"localhost:9100\", job=\"node\"}[5m])*8 or irate(node_network_receive_bytes{device=\"eno1\", instance=\"localhost:9100\", job=\"node\"}[5m])*8",
     "legendFormat": "rx"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "description": "Disk usage on the server",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_weighted_seconds_total{device=\"sda\", instance=\"localhost:9100\", job=\"node\"}[5m])",
     "legendFormat": "I/O"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{job=\"google-ping-job\"}",
     "legendFormat": "google"
    },
    {
     "expr": "probe_duration_seconds{job=\"cloudflare-ping-job\"}",
     "legendFormat": "cloudflare"
    }
   ]
  }
 ]
}